### ISSUE TITLE
Koivisto 6.0 release post

### ISSUE THREAD

**Issue by Luecx** [Luecx/Koivisto#119]
Howdy fellow chess enthusiasts,

Not long ago we have released Koivisto 5.0 with the goal of making a unique engine based on training data generated by its previous version, with its own tuning and inference code. Since 5.0, which marked the release of our first neural network, many things happened. Firstly, we tweaked the feature transformer in a way that we require more than just one accumulator. Making the input to the network effectively relative to the side to move, we gained about 30 Elo. Further patches followed tweaking the search, making it more aggressive since the prediction of the network outperforms our previous RME.

Furthermore we introduced a completely new time-management scheme which, as far as we know, has never been tested in any other engine. We use the internal node counts for subtrees to check how many good moves at the root there are and based on that, increaes or decrease the time we spend on the search.

Lastly, we took over one week to generate 2^24 = 16.777M games. Resulting in approximately 1 billions fens which are scored using a depth 10 search as well as the game outcome. The results surpassed our expectations by a big margin resulting in:

```
ELO   | 88.83 +- 3.46 (95%)
CONF  | 10.0+0.10s Threads=1 Hash=16MB
GAMES | N: 20000 W: 7664 L: 2659 D: 9677
```

Since 5.0, we also tracked the elo changes compared to 5.0. The entire list can be found inside our wiki.

[https://github.com/Luecx/Koivisto/wiki/Regression-tests](url)

Latest regression seems to result in about 200 Elo compared to 5.0. Since we are far from done with the network, yet want to releae as soon as we pass 100 Elo over the latest release, we decided to release Koivisto 6.0 today.

```
ELO   | 199.07 +- 7.17 (95%)
CONF  | 10.0+0.10s Threads=1 Hash=16MB
GAMES | N: 6216 W: 3568 L: 351 D: 2297
```

The compiled executables can be found on our release page here.

Kim & Finn

**Comment by altarchess** [comment]
Posted
