### ISSUE TITLE
avx512 compile

### ISSUE THREAD

**Issue by Ipmanchess** [Luecx/Koivisto#120]
Would like to see Koivisto also as a avx512 compile in near future!

Ofcourse if some checks are needed i can always test it out on my i9 7980XE where i running avx512 engines..

Kind regards,
Ipman.

**Comment by altarchess** [comment]
Finn has been planning to do avx512 for tcec, so this is def on the to-do list :)

**Comment by Luecx** [comment]
Working on it now. Let's see if I can squeeze out a few nps :)

**Comment by Ipmanchess** [comment]
Thanks!

Koivisto needs to try enter my lists ;)
[http://ipmanchess.yolasite.com/i9-7980xe.php](url)

**Comment by Ipmanchess** [comment]
My Tournament  2021
                                 
1   Koivisto 6.0 x64 avx2  +271  +756/=141/-103 82.65%  826.5/1000
2   Koivisto 5.0 x64 avx2  -271  +103/=141/-756 17.35%  173.5/1000

TC: **1sec+0sec.** Just to check your engine doesn't get Time Forfeits ,and = **0 zero** ,Perfect!!

Engine                 Depth       Time   Games     Moves  Average Forfeit  Book Depth     MIDG   EARLY    ENDG    LATE
Koivisto 6.0 x64 avx   9.51    0:12:11    1000     58371    0.01     0     2977  2.98    10.76 | 10.84 | 8.34 | 7.28
Koivisto 5.0 x64 avx   8.71    0:11:14    1000     58194    0.01     0     2981  2.98    10.15 | 10.48 | 7.43 | 5.88

**Comment by Luecx** [comment]
So I got something to work. Sadly I am unable to validate this for the AVX512 part neither am I sure if the SSE code is as fast as it should be. @Ipmanchess could you try to compile yourself?

```
git clone https://github.com/Luecx/Koivisto.git
git checkout avx512support
cd src_files/
make release
```

This should produce 3 binaries inside the `/bin` folder. Running them inside the command line using `./Koivisto_6.0.... bench` should run a search on 50 positions which will take around 4. Can you validate that the bench of all the 3 executables match?

Greetings
Finn

**Comment by Luecx** [comment]
If not possible, I can also send you 3 binaries if you tell me the OS you work on.

**Comment by Luecx** [comment]
Okay So I would like you to download the sources from here:

https://github.com/Luecx/Koivisto/tree/avx512support

Click on the download button as zip.

Unpack it somewhere.

Next, get the network file from here:

https://github.com/Luecx/KoivistoNetworks/tree/240b52215d703ebf16de5872927b5c86c5bb68e4


-------


1) paste the network file anywhere inside the unpacked koivisto folder
2) go into src_files/
3) make release EVALFILE=pathToWhereYouPlacedTheNetwork
4) go into the bin/ folder, run the 3 exes from command lines using `./Koivisto....  bench` This will produce a bench value which should be the same for all of them and a different nps value which should be largest for AVX512 and lowest for SSE. I would like you to paste the bench results here

**Comment by Ipmanchess** [comment]
Thanks for fixing avx512 ,it's compiling and working great now with a very nice speed up!!
I have given bench screens in discord ,don't know how to put here..

Kind regards,
Ipman.
