### ISSUE TITLE
where is the NN file ?

### ISSUE THREAD

**Issue by tissatussa** [Luecx/Koivisto#140]
it seems Koivisto (6.16) uses some Neural Network but i see no UCI option for it .. also the Linux binary is under 1 Mb, so i guess a NN must be embedded .. did you train it uniquely for Koivisto ?  I find no info about this.

**Comment by altarchess** [comment]
The net is embedded. Current default net can be found [here](https://github.com/Luecx/KoivistoNetworks/tree/8c4c358aed37b3fb3bfbc6ca8a17fc60f93c0048)

For more information about the evaluation click [here](https://github.com/Luecx/Koivisto/wiki/Evaluation)

**Comment by Luecx** [comment]
As @altarchess already stated the important parts, I will add that:

The file format is most likely not compatible with other engines. Beside the network architecture being different (smaller) compared to other engines, our discretisation may be different.

The Network should be about 770kB if I remember correctly. So 1Mb for a non-static executable seems fine
