### ISSUE TITLE
Koivisto Search

### ISSUE THREAD

**Issue by hafaba** [Luecx/Koivisto#158]
FEN: 8/1p4r1/p2bb1pk/3p1p2/3P1PNP/q2BQ3/2R3K1/8 b - - 1 42

I have tested this position with Koivisto 7.2
42. .. Kh5 {black lose}
42. .. Kh7 {Black lose}
42. .. fxg4 {draw}

Koivisto 7.2
42...Kh5 43.Nf6+  Kh6 44.Qxe6  Qxd3 45.Rc8  Qd2+ 46.Kh1  Qd1+ 47.Kh2  Bxf4+ 48.Kg2  Rh7 49.Rg8  Qd2+ 50.Kf3  Qd3+ 51.Kxf4  Qxd4+ 52.Kf3  Qd1+ 53.Kg2  Qc2+ 54.Kg3  Qc3+ 55.Kh2  Qb2+ 56.Kg1  Qc1+ 57.Kf2  Qc2+ 
The position is equal  = 0.00   Depth:  43   00:01:55   3180 mN   TBhits = 11942687

Stockfish
42...fxg4 43.f5+  Kh7 44.fxe6  Re7 45.h5  Kg7 46.Rf2  g3 47.Rc2  a5 48.Qe2  Bf4 49.Bxg6  Qe3 50.Qg4  Bg5 51.Bf7  Qf4 52.h6+  Kh7 53.Qxg3  Qe4+ 54.Kg1  Qxc2 55.Qxg5  Qd1+ 56.Kh2  Qe2+ 57.Kg3  Qd3+ 58.Kh2 
White is slightly better  = 0.00   Depth:  46   00:00:28   901 mN   TBhits = 3989578

**Comment by altarchess** [comment]
I quickly checked with sf and at low depth it did not see that Kh5 is loosing, so in case it is, it's at least fairly deep. There are many positions where Koivisto & every other engine will have a hard time.
