### ISSUE TITLE
Endgame mistake : could win but draws

### ISSUE THREAD

**Issue by tissatussa** [Luecx/Koivisto#167]
8/8/4nN2/5K1p/5n2/4k3/8/8 b - - 3 22

![koivisto_v7 5_plays_Nc5_not_h4](https://user-images.githubusercontent.com/1109281/144062267-9eda6faa-0c04-4a47-bb71-01a0befb7e77.png)

Black to move.
Here Koivisto v7.5 played Nc5 ? and thus made a draw .. in this position only h4 ! wins.
The move h4 seems obvious, and many engines find / play it ..

I did the test in CuteChess GUI (on Linux) with hash 64 Mb and 1 thread.

**Comment by Luecx** [comment]
Did the engine have Tablebases?

**Comment by Luecx** [comment]
Also how sure are you Nc5 is not winning? The score is +8. This seems to be very decisive. Or is this some cursed win?

**Comment by Luecx** [comment]
So i checked the position. its infact not playing the optimal moves without TB but I would not say that this is easy or even trivial

**Comment by AlexBrunetti** [comment]
> Also how sure are you Nc5 is not winning? The score is +8. This seems to be very decisive. Or is this some cursed win?

Nc5 can't win because White plays NxP drawing immediately.

Alex

**Comment by Luecx** [comment]
I see.

Knowing that NNKvk is drawn is not known by Koivisto. Guess this is some edge case.

**Comment by tissatussa** [comment]
TBs were OFF in my CuetChess settings .. I used the online TBs at https://syzygy-tables.info to inspect this position .. indeed NNKvk is "some edge case" .. however NNKvkp is winning when one opponent (!) pawn is on the c-file or f-file .. eg. see https://en.wikipedia.org/wiki/Two_knights_endgame .. i mention this because many other engines DO move h4 in this position, although that might be luck : they might not be aware of the theory ..

**Comment by altarchess** [comment]
This should be fine as even 4 man TB's cover this case.
