### ISSUE TITLE
Invite Koivisto to participate in a chess engine tournament.

### ISSUE THREAD

**Issue by PabloDaniel0** [Luecx/Koivisto#182]
Hi, I am organizing a chess engine tournament, called OSCET, the aim of the tournament is to have the strongest open source engines compete in the tournament, to highlight its importance, I would like to invite you to participate in the tournament, details are here:
https://sites.google.com/view/oscet/take-part
**Registration form:** 
https://forms.gle/xE51X3S7bkuCQihB6
**Discord:**
https://discord.com/invite/e8H5QfdttV

**Comment by altarchess** [comment]
Feel free to include Koivisto in your tournament. Latest master can always be used.

**Comment by PabloDaniel0** [comment]
Thanks!

**Comment by Luecx** [comment]
@PabloDaniel0 i just had a quick look at your webpage. I recommend you add some impressum. Websites without an impressum are targeted by lawyers :)

**Comment by PabloDaniel0** [comment]
thank you very much for the advice, I have added this to the "About us" page and will improve it over time.
https://sites.google.com/view/oscet/about-us
