### ISSUE TITLE
CMakeLists.txt ?

### ISSUE THREAD

**Issue by tissatussa** [Luecx/Koivisto#190]
normally when i encounter a CMakeLists.txt, i execute the command `cmake -DCMAKE_BUILD_TYPE=Debug` to get a custom makefile, but doing so i get an error while compiling : _../networks/default.net not found_ .. the path is wrong then, because the net file DOES exist .. but when i compile by `make native` inside the source folder (as your readme states) all goes OK : no compile errors and the v8.0 binary (12.2 Mb) runs fine in CuteChess (v1.2.0 on Linux).

**Comment by altarchess** [comment]
When using cmake you need to manually download the network and put it in the correct folder.

**Comment by tissatussa** [comment]
mmm .. i guess you're wrong, try it. I did `git clone https://github.com/Luecx/Koivisto.git --recursive` and i have a file called `default.net` in /networks, just as the code says, but then ../networks/default.net is NOT found .. i think the relative path is wrong ($ROOT is defined as "../").

**Comment by Luecx** [comment]
uhh i see
you are actually correct. this is my bad

**Comment by Luecx** [comment]
the quick solution would be to manually move the network file to the correct folder. i usually use clion and clion automatically moves the cmakelists.txt into a folder so it does work for me. :) sorry for that.

**Comment by tissatussa** [comment]
i'm glad it helped you solve this issue .. please correct this, i will then again git clone the package and compile .. Btw. the CMakeLists method is not mentioned in your readme, we could use the provided makefile, but it's confusing.

**Comment by Luecx** [comment]
Can I close this issue?

**Comment by tissatussa** [comment]
> ... its mostly just for develpoment purpose ...

then you should remove the CMakeLists.txt from the package, to avoid confusion for users. Only keep 1 Makefile and point to that in the README. I thought cmake is rather common and should give a custom Makefile, which is best (?). But also a good default Makefile can contain customisation, eg. regarding the optimal CPU architecture of the user.    

> ... I am infact the only one that uses cmake ...

no, you're not :-)

> Can I close this issue?

Yes, for me it's clear now.
