### ISSUE TITLE
not able to make native

### ISSUE THREAD

**Issue by chessinfo99** [Luecx/Koivisto#197]
The syntax of the command is incorrect.
make: *** [makefile:40: native] Error 1
error found.
not able to compile even though everything is fine.

**Comment by Luecx** [comment]
whats your OS? is the network file existing?
On Windows the mkdir command could cause problems. A solution would be to remove the `mkdir ...bin` command from the makefile and use:

```
make native EXE=Koivisto.exe
```

This will place the engine within the source folder. Alternatively you can use some other shell like Msys2 or GitBash which can handle the mkdir command.

**Comment by chessinfo99** [comment]
Ah  understood , thank you for the help

**Comment by Luecx** [comment]
has this helped? did it work?
