### ISSUE TITLE
Koivisto crashing when starting game with a TB position

### ISSUE THREAD

**Issue by Matthies** [Luecx/Koivisto#199]
This uci sequence lets Koivisto 8.0 crash (I haven't tested latest master)

```
setoption name SyzygyPath value H:\syzygy\3-6
isready
ucinewgame
position fen 8/8/8/5N1p/4k2N/6K1/8/8 w - - 0 1
go wtime 11000 btime 11000 winc 1000 binc 1000
```

**Comment by Luecx** [comment]
uh thats interesting. Should clearly not happen. Infact it should just not search at all and directly return the tb move. I will investigate
