### ISSUE TITLE
macOS doesn't support --whole-archive

### ISSUE THREAD

**Issue by BlazingFire007** [Luecx/Koivisto#203]
MacBook Pro Intel 2020 - Monterey 12.2.1

I was able to compile successfully by replacing it with `-all_load` and `-noall_load`.

Though it seems that `-noall_load` is ignored, as the following message is generated:
```sh
ld: warning: option -noall_load is obsolete and being ignored
```

Here is the top of my modified makefile I used to build:
```
CC       = g++
SRC      = *.cpp syzygy/tbprobe.c
LIBS     = -pthread -Wl,-all_load -lpthread -Wl,-noall_load
FOLDER   = bin/
ROOT     = ../
NAME     = Koivisto
EVALFILE = $(ROOT)networks/default.net
EXE      = $(ROOT)$(FOLDER)$(NAME)_$(MAJOR).$(MINOR)
MINOR    = 6
MAJOR    = 8
ifeq ($(OS),Windows_NT)
    PREFIX := windows
    SUFFIX := .exe
else
    PREFIX := darwin
    SUFFIX := 
endif
```

**Comment by BlazingFire007** [comment]
Upon actually testing, I unfortunately get the error:
[1]    6976 bus error  ./Koivisto_8.6-x64-darwin-native

**Comment by Luecx** [comment]
Yeah Mac compiles seem to be difficult. We have observed the bus error before but we are not sure where it comes from. We are investigating. Thanks!

**Comment by Luecx** [comment]
Can you check if the last patch solves the problem?
