### ISSUE TITLE
Can you build a Korean chess engine?

### ISSUE THREAD

**Issue by cjssh1002** [Luecx/Koivisto#204]
Can you build a Korean chess engine?

**Comment by Luecx** [comment]
Can you add any more details to your request? What exactly do you want to see compiled?

**Comment by cjssh1002** [comment]
We Koreans exactly need a Korean chess (Janggi) engine. Although it is not yet internationally famous, it is very popular in Korea just like Go(Baduk).
Chinese chess(Xiangqi) Many engines exist. similar to Korean chess However, in Korean chess(Janggi), only the fairy-stockfish engine exists.
So, if you develop it first, you can preempt it.
I'll give you a site you can refer to.
And I am a janggi player. So I can help you.
I've asked many programmers to develop it, but I've been rejected every time.

https://en.wikipedia.org/wiki/Janggi
https://www.pychess.org/variants/janggi
https://github.com/cutechess/cutechess/issues/564

**Comment by Luecx** [comment]
the problem here is that the board is not 8x8 which would imply a simple translation including bitboards. this is not the case and since this engine is centered around bitboards, a complete rewrite of every single aspect of the engine would need to be done.

**Comment by cjssh1002** [comment]
fairy-stockfish "janggi engine" is also written in bitboards. And it's 10x9.
This means janggi board and coordinates. There are two types.
UCI protocol and CECP protocol.

![12처](https://user-images.githubusercontent.com/63978900/167265135-7185f3c5-e888-4c57-b758-36c91f398aee.PNG)
![23처](https://user-images.githubusercontent.com/63978900/167265136-cd826d55-2069-4c91-86d9-ad6ae01fc4a9.PNG)

**Comment by cjssh1002** [comment]
It is difficult to build a janggi engine by yourself. But if you are interested in janggi engine development, I can test it and help with enough opinions and rules and tactics for janggi.
Think carefully, there are hundreds of chess engines in Western chess. So the competition is very fierce. In particular, the world's strongest stockfish engine exists. Korean chess is still an undeveloped area. If you're interested in Korean chess, that's very advanced thinking. Because it's a more interesting coding challenge.

Of course, Fairy Stockfish is a very powerful janggi engine. This is because NNUE evaluation is performed. However, if you develop a janggi specialized engine, it is competitive enough.

**Comment by altarchess** [comment]
We are not interested in working on on a Korean Chess Engine.
