### ISSUE TITLE
FYI

### ISSUE THREAD

**Issue by iandoug** [Luecx/Koivisto#206]
Not an issue, just sharing some results.

See https://iandoug.com/?p=1593

PGN of finals attached if you want to take a look. All engines struggle with the pawn/bishop/knight pawn-blockade end games ... humans would take a pawn or push a pawn to make progress.

Congrats on good engine.

Cheers, Ian

[finals.zip](https://github.com/Luecx/Koivisto/files/8839591/finals.zip)

**Comment by Luecx** [comment]
thanks for the result. since this is not an active issue we will close this :)
Greetings and many thanks
Finn
