### ISSUE TITLE
Not unique build process and not same performances

### ISSUE THREAD

**Issue by tryingsomestuff** [Luecx/Koivisto#47]
Hi,

building the engine with "cmake . && make" in the root dir leads to a binary this is somehow -200Elo at least versus building using "make native" inside source dir.

This can be misleading quite a lot.

**Comment by Luecx** [comment]
200 Elo seems very extreme.
Considering that the engine is deterministic, such a elo difference could only be explained by having a 10x speedup.
What did you try to test them against each other?

**Comment by Luecx** [comment]
I will have a look at it myself real quick

**Comment by tryingsomestuff** [comment]
I'm using cutechess tourney. Short TC, 10s+0.1.
I'm running a 3s+0.1 now with koivisto_cmake_make and koivisto_native to show you some results.

Nps are indeed of my x5!

Koivisto_native : 2Mnps
Koivisto_cmake_root_dir : 0.4Mnps

```
Score of Koivisto vs Koivisto_cmake_make: 13 - 0 - 3 [0.906]
...      Koivisto playing White: 8 - 0 - 0  [1.000] 8
...      Koivisto playing Black: 5 - 0 - 3  [0.813] 8
...      White vs Black: 8 - 5 - 3  [0.594] 16
Elo difference: 394.1 +/- nan, LOS: 100.0 %, DrawRatio: 18.8 %
16 of 999999 games finished.
```

**Comment by tryingsomestuff** [comment]
Is the default cmake target a debug executable ?

**Comment by Luecx** [comment]
It is missing optimization flags.
I use CLion and I can choose if the cmake shall be used as a debug or release build.

I assume the default one is a debug build.

Thanks for pointing this out!

**Comment by Luecx** [comment]
Do you have an idea on how this could we solved?

Would is just help to just add O3 to the cmakelists.txt?

**Comment by tryingsomestuff** [comment]
Maybe the question is why having 2 build process ?

**Comment by tryingsomestuff** [comment]
Yes maybe adding
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O3")
might help

**Comment by Luecx** [comment]
One build-process is used for development using CLion. Although we strongly recommend using the makefile which is far more optimised.

**Comment by Luecx** [comment]
Have you tested if your proposed change works?

**Comment by tryingsomestuff** [comment]
yep, looks like same nps and strength follows

**Comment by Luecx** [comment]
Thank you! Will change it asap

**Comment by Luecx** [comment]
Fixed it. The last thing is that the version number is not correct when building with cmake. But this does not really matter :)
