### ISSUE TITLE
Draw evaluation

### ISSUE THREAD

**Issue by Luecx** [Luecx/Koivisto#66]
Some draw evaluation needs to be implemented.

Potentially this should be done using scaling techniques for the endgame.
This should contain different piece combinations with OCB and further known drawishness endgames.

Most likely this should also be incorporated with the tuner.

**Comment by altarchess** [comment]
Some unfortunate cases fixed https://github.com/Luecx/Koivisto/commit/24d9366d0fd35c0105e96ce2891e60b8586a0609
Issues like in https://tcec-chess.com/#div=l3&game=11&season=21 still remain tho.

**Comment by altarchess** [comment]
as HCE is eventually beeing replaced with some type of NN this isn't relevant anymore.
